package main

const (
	FormatDbdiagramIo     = "dbdiagram.io"
	FormatGraphql         = "graphql"
	FormatJpaKotlin       = "jpa-kotlin"
	FormatJpaKotlinData   = "jpa-kotlin-data"
	FormatLiquibase       = "liquibase"
	FormatOctopus         = "octopus"
	FormatOptiStudio      = "opti-studio"
	FormatPlantuml        = "plantuml"
	FormatQuickdbd        = "quickdbd"
	FormatSchemaConverter = "schema-converter"
	FormatSqlH2           = "h2"
	FormatSqlMysql        = "mysql"
	FormatSqlOracle       = "oracle"
	FormatSqlPostgresql   = "postgresql"
	FormatSqlSqlite3      = "sqlite3"
	FormatSqlSqlserver    = "sqlserver"
	FormatStaruml2        = "staruml2"
	FormatXlsx            = "xlsx"

	ColTypeString   = "string"
	ColTypeLong     = "long"
	ColTypeInt      = "int"
	ColTypeFloat    = "float"
	ColTypeDouble   = "double"
	ColTypeBoolean  = "boolean"
	ColTypeText     = "text"
	ColTypeDate     = "date"
	ColTypeTime     = "time"
	ColTypeDateTime = "datetime"
	ColTypeBlob     = "blob"
)
