package main

const (
	FormatDbdiagramIo     = "dbdiagram.io"
	FormatGraphql         = "graphql"
	FormatJpaKotlin       = "jpa-kotlin"
	FormatJpaKotlinData   = "jpa-kotlin-data"
	FormatLiquibase       = "liquibase"
	FormatOctopus         = "octopus"
	FormatOptiStudio      = "opti-studio"
	FormatPlantuml        = "plantuml"
	FormatQuickdbd        = "quickdbd"
	FormatSchemaConverter = "schema-converter"
	FormatSqlH2           = "h2"
	FormatSqlMysql        = "mysql"
	FormatSqlOracle       = "oracle"
	FormatSqlPostgresql   = "postgresql"
	FormatSqlSqlite3      = "sqlite3"
	FormatSqlSqlserver    = "sqlserver"
	FormatStaruml2        = "staruml2"
	FormatXlsx            = "xlsx"

	ColTypeBlob     = "blob"
	ColTypeBoolean  = "boolean"
	ColTypeDate     = "date"
	ColTypeDateTime = "datetime"
	ColTypeDouble   = "double"
	ColTypeFloat    = "float"
	ColTypeInt      = "int"
	ColTypeLong     = "long"
	ColTypeString   = "string"
	ColTypeText     = "text"
	ColTypeTime     = "time"

	FlagGraphqlPackage   = "graphqlPackage"
	FlagPackage          = "package"
	FlagRelation         = "relation"
	FlagRemovePrefix     = "removePrefix"
	FlagReposPackage     = "reposPackage"
	FlagSourceFormat     = "sourceFormat"
	FlagTargetFormat     = "targetFormat"
	FlagUniqueNameSuffix = "uniqueNameSuffix"
	FlagNotNull          = "notNull"
)
