FROM golang:1.16
ARG userName
ARG groupName
RUN addgroup $groupName || true
RUN adduser --disabled-password --gecos "" --force-badname --ingroup $groupName $userName || true
USER $userName
WORKDIR /app
COPY . /app
CMD ["make", "clean", "vendor", "compile"]