package octopus

const (
	ColTypeBinary   = "binary"
	ColTypeBit      = "bit"
	ColTypeBlob     = "blob"
	ColTypeBlob16   = "blob16"
	ColTypeBlob24   = "blob24"
	ColTypeBlob32   = "blob32"
	ColTypeBlob8    = "blob8"
	ColTypeBoolean  = "boolean"
	ColTypeChar     = "char"
	ColTypeDate     = "date"
	ColTypeDateTime = "datetime"
	ColTypeDecimal  = "decimal"
	ColTypeDouble   = "double"
	ColTypeEnum     = "enum"
	ColTypeFloat    = "float"
	ColTypeGeometry = "geometry"
	ColTypeInt      = "int"
	ColTypeInt16    = "int16"
	ColTypeInt24    = "int24"
	ColTypeInt32    = "int32"
	ColTypeInt64    = "int64"
	ColTypeInt8     = "int8"
	ColTypeJSON     = "json"
	ColTypeLong     = "long"
	ColTypePoint    = "point"
	ColTypeSet      = "set"
	ColTypeString   = "string"
	ColTypeText     = "text"
	ColTypeText16   = "text16"
	ColTypeText24   = "text24"
	ColTypeText32   = "text32"
	ColTypeText8    = "text8"
	ColTypeTime     = "time"
	ColTypeVarchar  = "varchar"
	ColTypeYear     = "year"
)
