on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  build-nix:
    strategy:
      matrix:
        arch: [amd64, arm64]
        os: [linux, darwin]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Set version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set environments
        if: ${{ matrix.os != 'windows' }}
        run: echo "BINARY=oct" >> $GITHUB_ENV

      - name: Build ${{ matrix.os }}-${{ matrix.arch }}
        run: |
          go mod vendor
          go build -ldflags "-s -w -X main.buildDateVersion=`date -u +.b%y%m%d-%H%M%S`" -v -o ${{ env.BINARY }}
          zip oct-${{ matrix.os }}-${{ matrix.arch }}-${{ env.RELEASE_VERSION }}.zip ${{ env.BINARY }}
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

      - name: release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: oct-${{ matrix.os }}-${{ matrix.arch }}-${{ env.RELEASE_VERSION }}.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: octopus-db-tools release ${{ env.RELEASE_VERSION }}
