on:
  push:
    branches:
      - "develop"
    tags:
      - "!*"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: |
          go mod vendor
          GO111MODULE=on go test -mod=vendor -v -count=1 ./...
